### ISSUE TITLE
树姐，这里为什么要对投射矩阵进行平移操作

### ISSUE THREAD

**Issue by wjx10210** [zhangyeyan/360-Surround-View-CUDA-Project#1]
<img width="465" alt="image" src="https://github.com/sesmfs/360-Surround-View-CUDA-Project/assets/48514154/c30f2886-db3d-4d03-b24c-6b0b8af001dd">

**Comment by wjx10210** [comment]
> <img alt="image" width="465" src="https://private-user-images.githubusercontent.com/48514154/300247188-c30f2886-db3d-4d03-b24c-6b0b8af001dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MjA4NzYsIm5iZiI6MTcwNjUyMDU3NiwicGF0aCI6Ii80ODUxNDE1NC8zMDAyNDcxODgtYzMwZjI4ODYtZGIzZC00ZDAzLWIyNGMtNmIwYjhhZjAwMWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA5MjkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NDA2ZWE4NzUxODZhZWMyZDA2NTdlZGFmM2M4NTkzYTgwZTE3ZmQ4ZmFlZTcyM2Y4ZTg3ODcwYWY3MTZhMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h0FxY9BEY7MT9yQCh8ck0mBVuI21U1PXTkZQS7G4uzQ">

**Comment by wuba-pat** [comment]
你也是树姐的粉丝吗
